# Generated by Django 2.0.4 on 2018-09-02 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20180902_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.ForeignKey(db_column='sno', on_delete=django.db.models.deletion.PROTECT, related_name='aaa', to='demo.Subject', verbose_name='所属学科'),
        ),
    ]
