# Generated by Django 2.0.4 on 2018-09-10 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20180902_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('no', models.AutoField(db_column='no', primary_key=True, serialize=False, verbose_name='编号')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=40, verbose_name='口令')),
                ('email', models.CharField(max_length=255, verbose_name='邮箱')),
                ('counter', models.IntegerField(default=3, verbose_name='票数')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'tb_user',
            },
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '讲师', 'verbose_name_plural': '讲师'},
        ),
    ]
