# Generated by Django 2.0.4 on 2018-09-12 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_user_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, default='1970-01-01'),
        ),
        migrations.AlterField(
            model_name='user',
            name='title',
            field=models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs.'), ('MS', 'Ms.')], default='', max_length=3),
        ),
    ]
