# Generated by Django 2.0.4 on 2018-09-13 14:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_auto_20180913_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='time',
            field=models.DateField(db_column='time', default=django.utils.timezone.now, verbose_name='时间'),
            preserve_default=False,
        ),
    ]
