# Generated by Django 2.0.4 on 2018-09-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_teacher_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.ManyToManyField(related_name='Subjects', to='demo.Subject'),
        ),
    ]
